[package]
name = "kinun"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.13.1"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v3.0.0" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true
